# Site wide configuration

title: "Zork Network"
description: "The Zork Network is Coming Soon!"
#if you modify locale please have a look at _data/messages.yml too
locale: en
#for meta name="author" :
author: "Barbazzo Fernap"

#Target date in UTC / GMT
countdown:
  theme: red
  year: 2026
  month: 1
  day: 1
  hour: 0
  minute: 0

# Site owner
owner:
  name: "Zork Network developers"
  email: "admin@zork.network"
  twitter: "zorkcoin"
  discord: "Wxc8GcHaT7"
  github: "ZorkNetwork"
  aboutlink:
    url: "mailto:admin@zork.network"
    caption: "Administrator"


# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
